### ISSUE TITLE
Release of fife 0.4.0

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#939]
That must be done for it:

**Tickets:**

* [x] #938 cmake/FindFifeChan.cmake does not find fifechan.hpp
* [x] #935 Compile guide for Windows
* [x] #907 How to package fifengine correctly?
* [x] #802 Package a new dev kit
* [x] #526 Uninstaller Doesn't Remove fife Module
* [x] #505 Windows package should download python if required

**Optimal Tickets:**

* [x] #575 Improve build system shared library support on linux (is that done with cmake maybe?)

**Fifechan 0.1.3 is  released.**

**Comment by LinuxDonald** [comment]
fifechan 0.1.3 is out: https://github.com/fifengine/fifechan/releases

**Comment by Beliaar** [comment]
@LinuxDonald sounds ok to me.

**Comment by prock-fife** [comment]
looks pretty good.  I would almost lean toward only fixing #938 and the rest are optional.

**Comment by prock-fife** [comment]
oh and nice work on fifechan 0.1.3

**Comment by LinuxDonald** [comment]
@jakoch can we do the release 0.4.0?
