### ISSUE TITLE
remove boost:regexp - replace with std:regexp

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#940]
The idea to remove boost:regexp and replace it with [std:regexp](http://en.cppreference.com/w/cpp/regex) comes from here https://github.com/fifengine/fifengine/issues/802#issuecomment-243278764.
For some pro's and con's see StackOverflow: [Boost:Regex cs. C11 Regex](http://stackoverflow.com/questions/7589672/boost-regex-vs-c11-regex)

- we need to check compilers on all platforms, if they support c11/std:regexp
   - [x] win `MSVC14`
   - [ ] linux (gcc)
          regexp support landed with [gcc 4.9 ](http://stackoverflow.com/a/23478698/1163786)
          gcc on travis = `Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`
       - [ ] **This is a blocker. We need to update gcc / libstdc++ on Travis**
   - [x] mac `Apple LLVM version 7.3.0 (clang-703.0.31)`
- other compatibility issues to consider? 
- speed?

**todo**
- [x] [replace boost:regexp code](https://github.com/fifengine/fifengine/search?utf8=%E2%9C%93&q=boost%3A%3Aregex) with std:regexp code
- [x] remove dependency boost:regexp

**Comment by LinuxDonald** [comment]
gcc should now be ready https://github.com/fifengine/fifengine/commit/87bb754d077d0b4f5592e7eb92dea554af5ce162
